baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "westim.github.io" # the base hostname & protocol for your site.
repository: westim/westim.github.io

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

# header text
title: Tim West
header: Software Engineer in Test in Newark, DE

# for welcome page
# to replace image go to index.html
email:
  address: "timothy.k.west@gmail.com"
  text: "timothy.k.west (at) gmail.com"

# disqus comment
disqus:
    shortname: "test" #your disqus comment short name

# google analytics
google:
    tracking-id: "" #your tracking id here

# If any plugins are added here, make sure to update the Gemfile as well
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

github: [metadata]
